In [1]:
from perfetto.trace_processor import TraceProcessor
import pandas as pd

In [2]:
tp = TraceProcessor(trace='benchmark_merge_update_dense/test_update_insert_random_float_data.pftrace')

In [5]:
def time_for_merge_internal(tp):
    query = tp.query(
        "SELECT name, dur as dur_ns, dur / 1e9 as dur_s FROM slice WHERE name = 'merge_internal' ORDER BY ts"
    )
    merge_internal = query.as_pandas_dataframe().infer_objects()
    # The first run is a warmup drop it
    merge_internal = merge_internal.iloc[1:]
    display(merge_internal["dur_s"].describe())
    return merge_internal

In [6]:
time_for_merge_internal(tp)

count    10.000000
mean      1.913730
std       0.023304
min       1.880913
25%       1.900221
50%       1.904140
75%       1.935609
max       1.945830
Name: dur_s, dtype: float64

              name      dur_ns     dur_s
1   merge_internal  1940500576  1.940501
2   merge_internal  1945829558  1.945830
3   merge_internal  1899308099  1.899308
4   merge_internal  1904383232  1.904383
5   merge_internal  1934821876  1.934822
6   merge_internal  1880912504  1.880913
7   merge_internal  1935870964  1.935871
8   merge_internal  1903897472  1.903897
9   merge_internal  1902958672  1.902959
10  merge_internal  1888820921  1.888821

In [9]:
query = tp.query(
    "SELECT * FROM slice WHERE name = 'merge' ORDER BY ts"
)
query.as_pandas_dataframe().infer_objects()

,id,ts,dur,track_id,category,name,depth,parent_id,arg_set_id,thread_ts,thread_dur,thread_instruction_count,thread_instruction_delta,cat,slice_id
0,22,56057039937023,7997089,4,arcticdb.processing,merge,2,21,19,None,None,None,None,arcticdb.processing,22
1,24,56057042785367,22911124,3,arcticdb.processing,merge,2,23,19,None,None,None,None,arcticdb.processing,24
2,27,56057047963135,14380366,4,arcticdb.processing,merge,2,21,26,None,None,None,None,arcticdb.processing,27
3,37,56057056250089,8367000,8,arcticdb.processing,merge,2,36,19,None,None,None,None,arcticdb.processing,37
4,42,56057062978738,6890551,4,arcticdb.processing,merge,2,21,28,None,None,None,None,arcticdb.processing,42
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12095,15406,56090520902004,11822864,19,arcticdb.processing,merge,2,15346,33,None,None,None,None,arcticdb.processing,15406
12096,15407,56090532749212,11422076,19,arcticdb.processing,merge,2,15346,34,None,None,None,None,arcticdb.processing,15407
12097,15408,56090544191501,8884515,19,arcticdb.processing,merge,2,15346,35,None,None,None,None,arcticdb.processing,15408
12098,15409,56090553096449,7334930,19,arcticdb.processing,merge,2,15346,36,None,None,None,None,arcticdb.processing,15409
12099,15410,56090560445586,7487946,19,arcticdb.processing,merge,2,15346,37,None,None,None,None,arcticdb.processing,15410